/* eslint-disable max-len */
export const questions= [
    {
        'question': 'Quel est le taux de fiabilité du préservatif masculin après un an d\'utilisation ?',
        'answerIndex': 1,
        'answers': [
            '100%',
            '97%',
            '50%',
        ],
        'category': 'Contraception',
        'caption': 'Chiffres de la Haute Autorité de Santé.',
        'link': 'https://www.has-sante.fr/upload/docs/application/pdf/2013-04/efficacite-methodes-contraceptives.pdf',
    },
    {
        'question': 'Le préservatif féminin est remboursé par l\'Assurance Maladie.',
        'answerIndex': 1,
        'answers': [
            'vrai',
            'faux',
        ],
        'category': 'Contraception',
        'caption': 'Le préservatif féminin, tout comme le gel spermicide, n\'est pas remboursé par l\'Assurance Maladie.',
        'link': 'https://www.service-public.fr/particuliers/vosdroits/F707',
    },
    {
        'question': 'Le DIU (stérilet) est efficace ...',
        'answerIndex': 1,
        'answers': [
            '- de 2 ans',
            'entre 4 et 10 ans',
            '+ de 10 ans',
        ],
        'category': 'Contraception',
        'caption': 'La durée d\'efficacité du DIU se situe entre 4 et 10 ans selon le modèle.',
        'link': 'https://www.service-public.fr/particuliers/vosdroits/F707',
    },
    {
        'question': 'Quel est le taux de fiabilité du gel spermicide après un an d\'utilisation ?',
        'answerIndex': 2,
        'answers': [
            '100%',
            '92%',
            '78%',
        ],
        'category': 'Contraception',
        'caption': 'Chiffres de la Haute Autorité de Santé.',
        'link': 'https://www.has-sante.fr/upload/docs/application/pdf/2013-04/efficacite-methodes-contraceptives.pdf',
    },
    {
        'question': 'Quel est le taux de fiabilité de la pilule contraceptive après un an d\'utilisation ?',
        'answerIndex': 0,
        'answers': [
            '98%',
            '90%',
            '50%',
        ],
        'category': 'Contraception',
        'caption': 'Chiffres de la Haute Autorité de Santé.',
        'link': 'https://www.has-sante.fr/upload/docs/application/pdf/2013-04/efficacite-methodes-contraceptives.pdf',
    },
    {
        'question': 'La pilule du lendemain doit être prise au plus tard ...',
        'answerIndex': 1,
        'answers': [
            '24h après le rapport à risque',
            '3 à 5 jours après le rapport à risque',
            'deux semaines après le rapport à risque',
        ],
        'category': 'Contraception',
        'caption': 'La contraception d\'urgence hormonale ou "pilule du lendemain" doit être prise si possible dans les douze heures qui suivent le rapport sexuel mal protégé, et au plus tard dans les 3 à 5 jours en fonction du contraceptif.',
        'link': 'https://www.ameli.fr/assure/sante/themes/contraception-urgence/prendre-procurer-pilule-lendemain',
    },
    {
        'question': 'La pilule du lendemain est disponible gratuitement et anonymement en pharmacie si vous être mineur.e.',
        'answerIndex': 0,
        'answers': [
            'vrai',
            'faux',
        ],
        'category': 'Contraception',
        'caption': 'Vous pouvez obtenir la "pilule du lendemain" sans prescription médicale, gratuitement et de manière anonyme en pharmacie,  ou auprès de l\'infirmière scolaire de votre établissementsi vous êtes collégienne ou lycéenne.',
        'link': 'https://www.ameli.fr/assure/sante/themes/contraception-urgence/prendre-procurer-pilule-lendemain',
    },
    {
        'question': 'Les jeunes filles de 12 à 25 ans peuvent obtenir gratuitement différents types de contraception (pilule, implant, stérilet...).',
        'answerIndex': 1,
        'answers': [
            'oui, directement en pharmacie',
            'oui, après consultation avec leur médecin généraliste ou gynécologue',
            'non',
        ],
        'category': 'Contraception',
        'caption': 'Les jeunes femmes de moins de 26 ans peuvent obtenir gratuitement et de façon anonyme la pilule contraceptive, la contraception d\'urgence hormonale, se faire poser un implant ou un dispositif intra-utérin (stérilet ou diaphragme). Les consultations et examens nécessaires liés à la contraception sont également pris en charge.',
        'link': 'https://www.infos-jeunes.fr/dispositifs/contraception-gratuite-et-anonyme-pour-les-12-25-ans',
    },
    {
        'question': 'Le sigle IST signifie Infection Sexuellement Transmisible.',
        'answerIndex': 0,
        'answers': [
            'vrai',
            'faux',
        ],
        'category': 'IST',
        'caption': 'Les infections sexuellement transmissibles (IST), autrefois appelées maladies sexuellement transmissibles (MST), sont des infections pouvant être transmises lors des relations sexuelles, avec ou sans pénétration.',
        'link': 'https://www.ameli.fr/assure/sante/themes/mst-ist/maladies-infections-sexuellement-transmissibles',
    },
    {
        'question': 'En France, quel pourcentage représentent les jeunes chaque année parmis les diagnostics de séropositivité ?',
        'answerIndex': 0,
        'answers': [
            '50%',
            '38%',
            '12%',
        ],
        'category': 'IST',
        'caption': 'En 2013, 726 jeunes de 15 à 24 ans ont découvert leur séropositivité VIH, soit 11,7% de l\'ensemble des découvertes et un taux, rapporté à la population du même âge, de 92 par million d\'habitants.',
        'link': 'http://beh.santepubliquefrance.fr/beh/2015/40-41/2015_40-41_1.html',
    },
    {
        'question': 'Que signifie le terme "Séropositif" ?',
        'answerIndex': 0,
        'answers': [
            'dont le sang contient des anticorps contre le VIH',
            'qui est infecté par une IST',
            'qui voit la vie du bon coté',
        ],
        'category': 'IST',
        'caption': 'Une personne est séropositive lorsqu\'elle a été infectée par le VIH, c\'est-à-dire que le VIH est entré dans son organisme et a commencé à se multiplier. À partir du moment où le corps d\'une personne est en contact avec le VIH, son système immunitaire (système de défense de l\'organisme) réagit en produisant des anticorps spécifiques.',
        'link': 'https://preventionsida.org/fr/vih/le-vih-cest-quoi/',
    },
    {
        'question': 'Le VIH est ...',
        'answerIndex': 1,
        'answers': [
            'un affaiblissement potentiellement mortel du système immunitaire',
            'un virus',
        ],
        'category': 'IST',
        'caption': 'Le VIH ou Virus de l\'Immunodéficience Humaine est un rétrovirus humain sexuellement transmissible. Il affaiblit le système immunitaire, et en l\'absence de traitement, est responsable du sida.',
        'link': 'https://www.santepubliquefrance.fr/maladies-et-traumatismes/infections-sexuellement-transmissibles/vih-sida',
    },
    {
        'question': 'Le SIDA est ...',
        'answerIndex': 0,
        'answers': [
            'un affaiblissement potentiellement mortel du système immunitaire',
            'un virus',
        ],
        'category': 'IST',
        'caption': 'Sans traitement approprié, le VIH affaiblit progressivement le système immunitaire. Le syndrome d\'immunodéficience acquise (SIDA) est le stade avancé de l\'infection à VIH. Il correspond à l\'apparition d\'une pathologie opportuniste liée à l\'affaiblissement du système immunitaire',
        'link': 'https://www.santepubliquefrance.fr/maladies-et-traumatismes/infections-sexuellement-transmissibles/vih-sida/la-maladie/#tabs',
    },
    {
        'question': 'Entre 2019 et 2021, le nombre de personnes diagnostiqués pour une infection à Chlamydiae a augmenté de ...',
        'answerIndex': 1,
        'answers': [
            '50%',
            '9%',
            '5%',
        ],
        'category': 'IST',
        'caption': 'Chiffres de Santé Publique France.',
        'link': 'https://www.santepubliquefrance.fr/maladies-et-traumatismes/infections-sexuellement-transmissibles/chlamydiae/la-maladie/#tabs',
    },
    {
        'question': 'Une infection à Chlamidyae non diagnostiquée / traitée peut causer une stérilité chez la femme.',
        'answerIndex': 0,
        'answers': [
            'vrai',
            'faux',
        ],
        'category': 'IST',
        'caption': 'Les infections à Chlamydiae peuvent provoquer des infections génitales hautes chez la femme, une stérilité, une grossesse extra-utérine et l\'atteinte du nouveau-né si la mère est infectée. Les risques de complications concernent surtout les femmes, mais les hommes peuvent également être touchés (épididymite, prostatite) et peuvent transmettre les chlamydiae à leur partenaire.',
        'link': 'https://www.santepubliquefrance.fr/maladies-et-traumatismes/infections-sexuellement-transmissibles/chlamydiae/la-maladie/#tabs',
    },
    {
        'question': 'La syphilis est l\'infection sexuellement transmissible la plus fréquente.',
        'answerIndex': 1,
        'answers': [
            'vrai',
            'faux',
        ],
        'category': 'IST',
        'caption': 'Les papillomavirus humains (HPV) sont l\'innfection sexuellement transmissible (IST) la plus fréquente. 80 % des femmes et probablement autant d\'hommes présentent une infection à HPV à un moment de leur vie.',
        'link': 'https://www.ameli.fr/assure/sante/themes/mst-ist/maladies-infections-sexuellement-transmissibles',
    },
    {
        'question': 'Les papillomavirus humains (HPV) peuvent être la cause de cancers.',
        'answerIndex': 0,
        'answers': [
            'vrai',
            'faux',
        ],
        'category': 'IST',
        'caption': 'Certains papillomavirus, dits à haut risque, sont en cause dans la survenue d\'un cancer. Dans le cancer du col de l\'utérus, les virus les plus fréquemment en cause sont les HPV de type 16 et 18 et ils sont présents dans plus de 70 % des cas. Les papillomavirus à haut risque sont également associés au développement de lésions précancéreuses et cancéreuses du vagin, de la vulve, de l\'anus, du pénis, de la gorge, des amygdales et de la langue.',
        'link': 'https://www.ameli.fr/assure/sante/themes/mst-ist/maladies-infections-sexuellement-transmissibles',
    },
    {
        'question': 'Une conjointe ou un conjoint peut obliger sa ou son partenaire à avoir des rapports sexuels.',
        'answerIndex': 1,
        'answers': [
            'vrai',
            'faux',
        ],
        'category': 'Consentement',
        'caption': 'Si avoir des rapports sexuels entre époux est un devoir conjugal, cela ne permet en aucun cas de forcer son conjoint à honorer cette obligation. En effet, il est bon de rappeler que contraindre son époux à avoir des rapports sexuels non désirés est un viol, le viol entre époux étant reconnu par la loi.',
        'link': 'https://www.alexia.fr/fiche/5931/refus-de-relations-sexuelles.htm',
    },
    {
        'question': 'Si une personne a donné une fois son accord à une activité sexuelle, cela signifie qu\'elle sera toujours d\'accord.',
        'answerIndex': 1,
        'answers': [
            'vrai',
            'faux',
        ],
        'category': 'Consentement',
        'caption': 'Le consentement doit être spécifique : donner son consentement une fois ne signifie pas donner son consentement pour toutes les fois suivantes. Même au milieu d\'une relation sexuelle, une personne devrait être libre de s\'interrompre ou de s\'arrêter à tout moment et de retirer son consentement.',
        'link': 'https://www.amnesty.org/fr/latest/campaigns/2021/06/ltay-toolkit-blog-how-to-talk-and-think-about-consent/',
    },
    {
        'question': 'Envoyer une photo ou une vidéo à caractère sexuel non sollicité (dick pic, sex tape) est puni par la loi.',
        'answerIndex': 0,
        'answers': [
            'vrai',
            'faux',
        ],
        'category': 'Consentement',
        'caption': 'En France, les termes de cyberflashing ou dick pic n\'apparaissent pas tels quels dans la loi. Pour autant, l\'article R.624-2 du code pénal peut s\'appliquer dans ce cas. Cet article dispose que l\'envoi non sollicité de « message contraires à la décence est puni de l\'amende prévue pour les contraventions de la 4e classe » à savoir 750 € maximum et jusqu\'à 1 500 € si l\'image est envoyée à un mineur de moins de 15 ans.',
        'link': 'https://www.cidj.com/actualite/dick-pic-envoyer-des-nudes-sans-consentement-est-puni-par-la-loi',
    },
    {
        'question': 'Ne pas dire "non" équivaut à donner son consentement.',
        'answerIndex': 1,
        'answers': [
            'vrai',
            'faux',
        ],
        'category': 'Consentement',
        'caption': ': le consentement sexuel doit être l\'expression d\'un choix libre et volontaire pour toutes les personnes concernées. Ne pas s\'exprimer ou ne pas dire « non » ne signifie pas donner son consentement. Les personnes inconscientes ou sous l\'emprise de l\'alcool ou de drogues ne peuvent pas donner leur consentement.',
        'link': 'https://www.cidj.com/actualite/dick-pic-envoyer-des-nudes-sans-consentement-est-puni-par-la-loi',
    },
    {
        'question': 'En France, quel part de la population déclare être homosexuelle ?',
        'answerIndex': 2,
        'answers': [
            '10%',
            '5%, 2%',
        ],
        'category': 'Orientation',
        'caption': 'Près de 83 % des Français déclarent être exclusivement hétérosexuels, contre environ 2 % affirmants êtres homosexuels',
        'link': 'https://fr.statista.com/statistiques/1022904/ventilation-par-sexualite-france/',
    },
    {
        'question': 'En France, en quelle année a été adoptée la loi sur le mariage pour tous ?',
        'answerIndex': 1,
        'answers': [
            '2013',
            '2011',
            '2006',
        ],
        'category': 'Orientation',
        'caption': 'La France est devenue en 2013 le 9ème pays européen et le 14ème pays au monde à adopter le mariage homosexuel.',
        'link': 'https://www.gouvernement.fr/action/le-mariage-pour-tous',
    },
    {
        'question': 'Dans combien de pays dans le monde l\'homosexualité est-elle interdite ?',
        'answerIndex': 0,
        'answers': [
            '69',
            '34',
            '11',
        ],
        'category': 'Orientation',
        'caption': '69 États dans le monde répriment l\'homosexualité. La loi y prévoit des sanctions ou les juges y prononcent des peines à l\'encontre des gays et lesbiennes. Dans onze pays, les relations homosexuelles sont passibles de la peine de mort.',
        'link': 'https://www.inegalites.fr/Dans-69-pays-sur-193-l-homosexualite-est-interdite',
    },
    {
        'question': 'La pansexualité désigne l\'attirance affective et/ou sexuelle pour les personnes du même sexe et du sexe opposé.',
        'answerIndex': 1,
        'answers': [
            'vrai',
            'faux',
        ],
        'category': 'Orientation',
        'caption': 'Le mot "pansexuel.le" désigne une personne qui aime un individu sans considération de son genre ou de son sexe. C\'est la personnalité qui compte.',
        'link': 'https://questionsexualite.fr/connaitre-son-corps-et-sa-sexualite/la-diversite-sexuelle/qu-est-ce-que-l-orientation-sexuelle',
    },
    {
        'question': 'En France, les violences anti-LGBT recensées ont été divisées par deux en cinq ans.',
        'answerIndex': 1,
        'answers': [
            'vrai',
            'faux',
        ],
        'category': 'Orientation',
        'caption': 'Au total sur l\'année 2021, les plaintes pour crimes et délits anti-LGBT+ ont augmenté de 28% par rapport à l\'année 2020, soit un doublement depuis 2016 (+ 104%) ! Des chiffres qui restent en deçà de la réalité puisque le ministère estime que seules 20% des victimes déposent une plainte.',
        'link': 'https://tetu.com/2022/05/17/17-mai-journee-mondiale-contre-homophobie-transphobie-chiffres-2022-violences-anti-lgbt/',
    },
    {
        'question': 'En France, quelle part des personnes transgenres déclare avoir fait une dépression suite à des actes transphobes ?',
        'answerIndex': 2,
        'answers': [
            '10%',
            '27%',
            '56%',
        ],
        'category': 'Orientation',
        'caption': 'En 2014, en France, 56% des personnes trans déclaraient avoir fait une dépression suite à des actes transphobes, et 18 % une tentative de suicide.',
        'link': 'https://www.radiofrance.fr/franceinter/les-personnes-lgbt-subissent-plus-de-discriminations-et-ca-a-des-repercussions-sur-leur-sante-3248978',
    },
    {
        'question': 'Les lubrifiants à base de corps gras sont incompatibles avec l\'utilisation d\'un préservatif.',
        'answerIndex': 0,
        'answers': [
            'vrai',
            'faux',
        ],
        'category': 'Contraception',
        'caption': 'Si vous appliquez un lubrifiant sur un préservatif, utilisez uniquement un gel lubrifiant à base d\'eau. Il ne faut jamais appliquer un produit gras comme de la vaseline, du beurre, de l\'huile, des pommades ou des crèmes... En effet, utiliser des produits contenant des corps gras altèrent le préservatif, le rendent poreux et augmentent donc les risques de rupture.',
        'link': 'https://www.doctissimo.fr/html/sexualite/mag_2000/mag0707/se_1953_lubri_preserv.htm',
    },
];